import numpy as np
from numpy.lib.stride_tricks import as_strided


class Conv2d1c:
    def __init__(self, filters, kernel_shape, weights_range=(-0.01, 0.01)):
        self.kernel_shape = kernel_shape
        self.kernels = np.random.default_rng().uniform(
            weights_range[0],
            weights_range[1],
            (filters, kernel_shape[0] * kernel_shape[1]),
        )

    def forward(self, input):
        self.x = input

        N, H, W = input.shape
        K_h, K_w = self.kernel_shape
        H_out = H - K_h + 1
        W_out = W - K_w + 1

        stride_N, stride_H, stride_W = input.strides

        patches = as_strided(
            input,
            shape=(N, H_out, W_out, K_h, K_w),
            strides=(stride_N, stride_H, stride_W, stride_H, stride_W),
        )

        self.patches = patches.reshape(N, H_out * W_out, K_h * K_w, order="F")
        return self.patches @ self.kernels.T

    def backward(self, grad):
        # grad.shape -> (N, number_patches, filters)
        # self.kernels.shape -> (filters, self.kernel_shape[0] * self.kernel_shape[1])
        # (grad @ self.kernels).shape -> (N, number_patches, filters) @ (filters, self.kernel_shape[0] * self.kernel_shape[1])
        # (grad @ self.kernels).shape -> (N, number_patches, self.kernel_shape[0] * self.kernel_shape[1])
        N, H, W = self.x.shape
        K_h, K_w = self.kernel_shape
        H_out = H - K_h + 1
        W_out = W - K_w + 1

        # grad @ self.kernels => Errors generated by patches
        patches_delta = grad @ self.kernels
        self.dX = np.zeros(self.x.shape)
        patch_idx = 0

        # Splitting error generated by patches into error generated by single inputs
        for row in range(H_out):
            for col in range(W_out):
                self.dX[:, row : row + K_h, col : col + K_w] += patches_delta[
                    :, patch_idx, :
                ].reshape(N, K_h, K_w)
                # += because patches overlap themselfs
                patch_idx += 1

        # grad.transpose(0, 2, 1).shape -> (N, filters, number_patches)
        # self.all_patches.shape -> (N, number_patches, self.kernel_shape[0] * self.kernel_shape[1])
        # self.dW.shape before np.sum -> (N, filters, number_patches) @ (N, number_patches, self.kernel_shape[0] * self.kernel_shape[1])
        self.dW = np.sum(grad.transpose(0, 2, 1) @ self.patches, axis=0)

        return self.dX, self.dW

    def adjust(self, alfa):
        self.kernels -= alfa * self.dW
